#!/bin/sh
# maintain /dev/disk/by-uuid, by-label and by-partuuid links
[ -n "$MDEV" ] || exit 0
case "$ACTION" in
  remove) for d in /dev/disk/by-*; do for l in "$d"/*; do [ "$(readlink "$l")" = "../../$MDEV" ] && rm -f "$l"; done; done ;;
  *) eval "$(blkid -o export /dev/$MDEV 2>/dev/null | grep -E '^(UUID|LABEL|PARTUUID)=' )"
     [ -n "$UUID" ] && mkdir -p /dev/disk/by-uuid && ln -sf ../../$MDEV /dev/disk/by-uuid/$UUID
     [ -n "$LABEL" ] && mkdir -p /dev/disk/by-label && ln -sf ../../$MDEV "/dev/disk/by-label/$LABEL"
     [ -n "$PARTUUID" ] && mkdir -p /dev/disk/by-partuuid && ln -sf ../../$MDEV /dev/disk/by-partuuid/$PARTUUID ;;
esac
exit 0
