#!/bin/sh
exec 2>&1
modprobe zram 2>/dev/null
[ -e /sys/block/zram0/disksize ] || { sleep 3600; exit 0; }
if ! grep -q "^/dev/zram0" /proc/swaps; then
  mem=$(awk "/MemTotal/{print \$2}" /proc/meminfo)
  echo zstd > /sys/block/zram0/comp_algorithm 2>/dev/null
  echo $((mem / 2))K > /sys/block/zram0/disksize
  mkswap /dev/zram0 >/dev/null && swapon -p 100 /dev/zram0
fi
exec sleep 2147483647
