# fstab, swap, services, bootloader (BIOS + UEFI), LUKS unlock initramfs, rewards
---
dontChroot: true
timeout: 1800
script:
    - command: "/usr/libexec/melon/cal-finish ${ROOT} ${USER}"
      timeout: 1800
