# the user becomes an administrator (wheel = sudo/doas and polkit admin), like in the console installer
---
defaultGroups:
    - name: users
      must_exist: true
      system: true
    - wheel
    - audio
    - video
    - input
    - render
    - plugdev
    - netdev
    - kvm
    - cdrom
    - lp
autoLoginGroup: autologin
doAutologin: false
sudoersGroup: ""
setRootPassword: true
doReusePassword: true
passwordRequirements:
    nonempty: true
    minLength: 1
    maxLength: -1
allowWeakPasswords: true
allowWeakPasswordsDefault: true
user:
    shell: /bin/bash
    forbidden_names: [ root, live ]
hostname:
    location: EtcFile
    writeHostsFile: true
    template: "melon-${first}"
    forbidden_names: [ localhost ]
