#!/bin/sh
exec 2>&1
# Wi-Fi authentication. Networks live in /etc/wpa_supplicant/wpa_supplicant.conf.
[ -r conf ] && . ./conf
IFACE=${IFACE:-$(for i in /sys/class/net/*; do [ -d $i/wireless ] && { echo ${i##*/}; break; }; done)}
[ -n "$IFACE" ] || { echo "no wireless interface found"; sleep 30; exit 1; }
exec wpa_supplicant -s -D nl80211 -i "$IFACE" -c /etc/wpa_supplicant/wpa_supplicant.conf
