# melon mdev rules
null        root:root 666
zero        root:root 666
full        root:root 666
random      root:root 666
urandom     root:root 666
tty         root:tty  666
console     root:tty  600
ptmx        root:tty  666
tty[0-9]+   root:tty  620
ttyS[0-9]+  root:dialout 660
fuse        root:root 666
kvm         root:kvm  660
rfkill      root:netdev 664
snd/.*      root:audio 660
dri/.*      root:video 666
fb[0-9]+    root:video 660
input/.*    root:input 660
uinput      root:input 660
video[0-9]+ root:video 660
sr[0-9]+    root:cdrom 660 =cdrom/ @ln -sf $MDEV cdrom
sd[a-z].*   root:disk 660 */usr/share/melon/mdev-disk
nvme.*      root:disk 660 */usr/share/melon/mdev-disk
vd[a-z].*   root:disk 660 */usr/share/melon/mdev-disk
mmcblk.*    root:disk 660 */usr/share/melon/mdev-disk
loop[0-9]+  root:disk 660
net/tun     root:netdev 660
# load drivers for new hardware, firmware is loaded by the kernel itself
$MODALIAS=.* root:root 0660 @modprobe -b -q "$MODALIAS"
